### ISSUE TITLE
Possible errors in nLSI and in the documentation

### ISSUE THREAD

**Issue by thellmundt** [r-spatialecology/landscapemetrics#215]
Hi all,

When calculating the Normalized Landscape Shape Index (nLSI) for various landscapes I noticed some odd things.

First of all, the documentation is identical to the documentation for the (not normalized) LSI and hence also reports the wrong formula - I suppose this might simply be a copy-paste error. 

However, and potentially more problematic: when calculating the metric, some of the values exceed the theoretically possible range of the nLSI of [0, 1].

Could it be that there is an error in the function somewhere? I've attached a screenshot of an example in which I found the nLSI for the second class to be greater than 1, which should be impossible if my understanding of the metric is correct.
 
![ls_example](https://user-images.githubusercontent.com/50458475/99878682-7ab4e200-2c07-11eb-8c62-a6db72b1e287.JPG)
![result_example](https://user-images.githubusercontent.com/50458475/99878685-7d173c00-2c07-11eb-84ed-77c710bb0d56.JPG)

Thanks in advance for any help!

Best regards,
Tobias

**Comment by thellmundt** [comment]
Calculating the metric for the same landscape in FRAGSTATS resulted in nLSI values of 0.103 and 0.118, so there seems to be something off with the package function.

I went through the calculation of the metric in detail and found that the actual edge of class 2 is much longer than the calculated maximum possible edge length (see screenshot below). This leads me to believe that the calculation of either of the two is incorrect, but I am not able to figure out what exactly the problem is.


![detail_1](https://user-images.githubusercontent.com/50458475/99883863-4acb0600-2c2a-11eb-915e-e377916fdf04.JPG)

**Comment by thellmundt** [comment]
I think I have found the reason for this error:

`lsm_c_nlsi_calc` relies on `lsm_c_te_calc` and `lsm_l_te_calc` to calculate the class edges and total edge. These two functions return edges in _meters_. The calculations for the nLSI require edges to be measured in _number of cell surfaces_ rather than meters according to [http://www.umass.edu/landeco/research/fragstats/documents/Metrics/Area%20-%20Density%20-%20Edge%20Metrics/Metrics/C124%20-%20nLSI.htm](url)

I tried converting the edge lengths from meters to cell numbers with
```
    resolution_x <- resolution[[1]]
    class_edge$value <- class_edge$value/resolution_x
    total_edge$value <- total_edge$value/resolution_x
``` 
which ultimately resulted in the same nLSI values than the one calculated in FRAGSTATS and hence seems to fix the issue!

The above solution does not account for potential differences in X and Y resolution, so that might need to be converted more carefully.

**Comment by Nowosad** [comment]
@thellmundt great investigative work! Thank you. 
I will wait for @mhesselbarth to confirm this issue and proposed solution. 
Btw - could you share your example raster with us?

**Comment by thellmundt** [comment]
I'm glad if I was able to help!
My example raster: [example_ls.zip](https://github.com/r-spatialecology/landscapemetrics/files/5579600/example_ls.zip)

**Comment by mhesselbarth** [comment]
I don't know why we decided to use the edge values in meters. I think there is a better solution which does not need to multiply the meters by the resolution, but simply use the adjacencies matrices. I started to fix it at the moment, however, I struggle to understand what the difference is between:

> B = number of cells on the boundary (perimeter) of the landscape
> Z = total length of landscape boundary (perimeter) given in number of cell surfaces

[FRAGSTATS manual](http://www.umass.edu/landeco/research/fragstats/documents/Metrics/Area%20-%20Density%20-%20Edge%20Metrics/Metrics/C124%20-%20nLSI.htm)

Can anyone help me out please 😄

**Comment by mhesselbarth** [comment]
Okay, fixed it: 47a27bd

Can you please try to run the following line of code to reinstall the latest version with the bug fix and check if results are correct now? 

```
remotes::install_github("r-spatialecology/landscapemetrics, ref = "lsi")
```

P.S. Nice side effect: I only did a very brief benchmark, but seems to be also slightly faster than before.

**Comment by mhesselbarth** [comment]
Reminder: Still have to fix documentation

**Comment by thellmundt** [comment]
Thank you very much for fixing this so quickly! 
The results seem to be correct now, at least for my data. 

There remains one difference in comparison to FRAGSTATS, but I'm unsure whether it's actually an issue or a desired property:

I've calculated the nLSI for a landscape that has a border ("padding") of several rows and columns of NA cells (which were somehow created by a reprojection), and found that these NA values actually make a difference in the calculation of the nLSI. In FRAGSTATS, the NA padding around the landscape is ignored and hence there is no difference in the nLSI.
I've attached two versions of the same landscape, both with padding and without, if you want to try for yourself.

[padding_examples.zip](https://github.com/r-spatialecology/landscapemetrics/files/5584569/padding_examples.zip)

**Comment by mhesselbarth** [comment]
Should be fixed in 47a27bd1. Please try to re-install and run again. 

However, we have 2 problems at the moment. 

According to the FRAGSTATS manual, we need _"[...] landscape area, including all internal background (in terms of number of cells) [...]"_. I am not sure how to count the background cells within the landscape and not count "padding" cells because both are `NA`. 

Also, we need _"[...] number of cells on the boundary (perimeter) of the landscape [...]"_ which currently only works for rectengular landscapes. Again, I am not sure how to count these cells for irregular shaped landscapes.

[Link to FRAGSTATS manual](http://www.umass.edu/landeco/research/fragstats/documents/Metrics/Area%20-%20Density%20-%20Edge%20Metrics/Metrics/C124%20-%20nLSI.htm)

**Comment by thellmundt** [comment]
I am not able to re-install the package anymore, I now get the error:
`Error: Failed to install 'landscapemetrics' from GitHub:
  (converted from warning) installation of package ‘C:/Users/Tobias/AppData/Local/Temp/RtmpQBdtHM/file223880e1cd1/landscapemetrics_1.5.1.tar.gz’ had non-zero exit status`
I also tried it with the option `R_REMOTES_NO_ERRORS_FROM_WARNINGS="false"` but that didn't fix it either.

Also, I found another (small) problem:
In the special case that a landscape consists of only one class which covers the entire landscape, the calculation of the NLSI prints the message `Warning: NAs introduced by lsm_c_nlsi ` and sets the value of the metric to an undefined value of `NaN` where it should be `NA` instead (or maybe even `0` instead? I am not sure what the correct value would be in that case). 
I don't know if this really is an issue because it only concerns that special case, but I guess it could potentially create problems for some users.

**Comment by Nowosad** [comment]
@thellmundt have you tried to restart R before installing new version?

**Comment by mhesselbarth** [comment]
I can't reproduce the installation issue. Also all CI checks we run on Windows, macOS and Linux are able to install the package?

> Also, I found another (small) problem: [...]

Fixed: ef631822
According to the manual, in this case nLSI should be `NA` because min(ei) = max(ei).

**Comment by mhesselbarth** [comment]
@Nowosad 

Any ideas what to do about: 


1. > According to the FRAGSTATS manual, we need "[...] landscape area, including all internal background (in terms of number of cells) [...]". I am not sure how to count the background cells within the landscape and not count "padding" cells because both are NA.

2. > Also, we need "[...] number of cells on the boundary (perimeter) of the landscape [...]" which currently only works for rectengular landscapes. Again, I am not sure how to count these cells for irregular shaped landscapes.

**Comment by bitbacchus** [comment]
I have no idea about this particular metric, but here is my shot :-)

> 1. > According to the FRAGSTATS manual, we need "[...] landscape area, including all internal background (in terms of number of cells) [...]". I am not sure how to count the background cells within the landscape and not count "padding" cells because both are NA.

Can't we just count before the padding happens here: https://github.com/r-spatialecology/landscapemetrics/blob/47a27bd13e1e3d0686554e0ce0aa46c4e419732c/R/lsm_c_lsi.R#L77

> 2. > Also, we need "[...] number of cells on the boundary (perimeter) of the landscape [...]" which currently only works for rectengular landscapes. Again, I am not sure how to count these cells for irregular shaped landscapes.

Are irregularly shaped landscapes even technically possible with landscapes based on `raster` and `matrix`? Especially when we count `NA` as part of the landscape ('internal background')?

**Comment by Nowosad** [comment]
Hi @mhesselbarth. I am not entirely sure that I understand all of the terminologies you've used. What are "the background cells"? 

Regarding the second question - let's say that we have a raster where NAs represent the outsides of the landscape. The simple way (probably not very fast, though), would be to reclassify all not-NA cells into one value, vectorize the landscape to create a  contour, and then extract cells based on the contour. The number of cells should equal to the perimeter.

**Comment by mhesselbarth** [comment]
As far as I understand the FRAGSTATS manual, "background cells" are NA cells within the landscape that should not be considered for most metrics, e.g. a large body of water that is not of interest. 

1.) 
> Can't we just count before the padding happens here 

That would at least help with the padding yes. But we still have the problem that we can not distinguish between NA that are within the landscape (e.g. water bodies that we need to count) and NA outside an irregular landscape (which we don't need to count). I tried to attach a very stupid figure of what I mean :) I think this case is not completely unlikely, since `raster::mask` could produce exactly such a landscape. 

![lsm](https://user-images.githubusercontent.com/29225293/100610004-f0424180-32dc-11eb-905e-86798b7fac33.png)

2.) 
That would be one approach, but I guess extremely slow and also the only metric that does not just rely on matrix calculations which I would not really like tbh.

**Comment by bitbacchus** [comment]
> That would at least help with the padding yes. But we still have the problem that we can not distinguish between NA that are within the landscape (e.g. water bodies that we need to count) and NA outside an irregular landscape (which we don't need to count). I tried to attach a very stupid figure of what I mean :) I think this case is not completely unlikely, since raster::mask could produce exactly such a landscape.

Yes, but we don't know anyway if the NAs at the edge of the landscape are there because the landscape is irregular, or because they are a lake, for example. And conceptually, all NAs should by definition not be part of the landscape, shouldn't they?

**Comment by mhesselbarth** [comment]
That is exactly the problem that we can not tell the difference. 

Regarding NAs in general, that's where FRAGSTATS is a bit unclear, but I think they do conceptually make a difference between the landscape boundary and NAs that are within the landscape (i.e. background).

**Comment by bitbacchus** [comment]
> Regarding NAs in general, that's where FRAGSTATS is a bit unclear, but I think they do conceptually make a difference between the landscape boundary and NAs that are within the landscape (i.e. background).

This sounds weird to me. Is a rectangular landscape with a lake (=NA) at the border still a rectangular landscape? And how do I know? 

> This is another good example if you now imagine the provided example landscapes have additional NAs in the center of them (e.g. the previous water body example)

But keeping track of a padding that is introduced by an internal landscapemetrics function is not too hard, is it?

**Comment by mhesselbarth** [comment]
> > Regarding NAs in general, that's where FRAGSTATS is a bit unclear, but I think they do conceptually make a difference between the landscape boundary and NAs that are within the landscape (i.e. background).
> 
> This sounds weird to me. Is a rectangular landscape with a lake (=NA) at the border still a rectangular landscape? And how do I know?

Not sure if we are actually talking about the same 😄 I am thinking of the example where e.g. a circular polygon was used to mask the original landscape scape. This will result in a non-rectangular landscape because all cells outside the circle will be NA. Those NA are not "background" but rather outside the boundary.

> > This is another good example if you now imagine the provided example landscapes have additional NAs in the center of them (e.g. the previous water body example)
> 
> But keeping track of a padding that is introduced by an internal landscapemetrics function is not too hard, is it?

But in the example of @thellmundt, the padding was not introduced by an internal `landscapemetrics` function but in a previous pre-processing step (reprojecting the raster).

**Comment by bitbacchus** [comment]
> Not sure if we are actually talking about the same smile I am thinking of the example where e.g. a circular polygon was used to mask the original landscape scape. This will result in a non-rectangular landscape because all cells outside the circle will be NA. Those NA are not "background" but rather outside the boundary.

Hm, okay. And if a previously internal background cell touches the new border it becomes part of the padding, right? If that's correct, an algorithm to count the landscape area could look like this:

1. mark and count all NA at the matrix' borders
2. for each marked NA, mark and count its direct NA neighbors 
3. repeat (probably recursively) 2 until none has any unmarked NA neighbors left
4. landscape size = matrix size - marked NA count

Then, we could measure the perimeter like this:

1. count all non-NA cells that have a marked NA as a direct neighbor

What do you think?

**Comment by mhesselbarth** [comment]
But how do we count/determine NAs at the matrix border if it's not a regular "padding", but rather a non-rectengular shaped raster?

**Comment by bitbacchus** [comment]
![landscapes](https://user-images.githubusercontent.com/19432439/100987569-f9d2e000-354e-11eb-8f06-cdad63da85ed.png)
like so?

**Comment by mhesselbarth** [comment]
😄 I just don't get it, but that's probably my problem...

So what happens in the case the "Resulting landscape" is the original input? I think that's a good example where I don't understand how to differentiate between grey and blue (technically)

**Comment by bitbacchus** [comment]
> So what happens in the case the "Resulting landscape" is the original input? I think that's a good example where I don't understand how to differentiate between grey and blue (technically)

Ah, that's easy. You start marking "grey" NA at the very borders of the input. I.e. all NA cells in the four vectors input[0, ] + input[max_x, ] + input[ , 0] and input[ , max_y]. They can't be internal NA, because they are at the border of the input matrix. Then you iteratively mark all NA cells that have a grey NA cell in their moore|queen neighborhood until you can't find any anymore. The blue NA cells are left over as the do only have blue or green cells as neighbors.

**Comment by mhesselbarth** [comment]
Got it...that makes sense I! 👍

**Comment by mhesselbarth** [comment]
I decided to update `landscapemetrics` on CRAN today and added the comment in the documentation of `lsm_c_nlsi` that currently the metric is only correct if no background is present and the landscape is rectangular. I figured at this point it is more important to update/fix the more general bug first.

**Comment by gponce-ars** [comment]
Hi,

Since my question seems to be related to this discussion, I decided to post it here. 

I'm using `landscapemetrics_1.5.2` and R-version is 4.0.3 on OSx. 

I have these:
- A classified raster with 4 categories (1-4).
- A 5m grid 
My goal:
To get the LPI values at each 5-m grid for one specific class(i.e. 3)

This is the resulting LPI (point shape) where each point has the corresponding LPI value at each cell based on the classified raster.

<img width="1672" alt="image" src="https://user-images.githubusercontent.com/20215136/112546860-3f721d80-8d77-11eb-9a4b-7a7f26465575.png">

There are two cases where I get NA's.  First, at the edges where no presence of any of the classes (i.e. in the image at the top left corner) and the other case, within the imagery (examples in red rectangles in image), where my class(3) is not present or just  few pixels scattered.  In the latter case, I have been just wrangling the resulting tables to switch LPI value from NA to a 0 in those cases when another class is present within the cell-grid, so I can discern from those truly NA's (top)?

Is there any way to get 0's instead of NA's in those cases where there's other classes within a cell-grid?

When resulting LPI is too low or 0 (no presence of pixels or few scattered ones), it is just set to NA, right? 

Best,
Guillermo

**Comment by mhesselbarth** [comment]
This is actually already fixed I think
